clear;
clc;

script_path = mfilename('fullpath');
scripts_dir = fileparts(script_path);
project_root = fileparts(scripts_dir);
data_file = fullfile(project_root, 'results', 'mpc_identification_profiles.mat');

loaded = load(data_file, 'profile_data', 'sample_time');
profiles = loaded.profile_data;
base_sample_time = loaded.sample_time;
decimation_values = [1, 5, 10, 20, 50];
selected_model = struct();

fprintf(['order,decimation,Ts,a1,a2,b1,b2,bias,pole1,pole2,' ...
    'one_step_rmse,free_run_rmse\n']);

for decimation = decimation_values
    training = cell(3, 1);

    for profile_index = 1:3
        training{profile_index}.y = profiles{profile_index}.y(1:decimation:end);
        training{profile_index}.u = profiles{profile_index}.u(1:decimation:end);
    end

    validation.y = profiles{4}.y(1:decimation:end);
    validation.u = profiles{4}.u(1:decimation:end);

    %% First-order affine model
    x1 = zeros(0, 3);
    target1 = zeros(0, 1);

    for profile_index = 1:3
        y = training{profile_index}.y;
        u = training{profile_index}.u;
        x1 = [x1; y(1:end-1), u(1:end-1), ones(numel(y) - 1, 1)]; %#ok<AGROW>
        target1 = [target1; y(2:end)]; %#ok<AGROW>
    end

    theta1 = x1 \ target1;
    y1 = validation.y;
    u1 = validation.u;
    one_step1 = [y1(1); [y1(1:end-1), u1(1:end-1), ones(numel(y1) - 1, 1)] * theta1];
    free_run1 = zeros(size(y1));
    free_run1(1) = y1(1);

    for sample_index = 2:numel(y1)
        free_run1(sample_index) = ...
            theta1(1) * free_run1(sample_index - 1) + ...
            theta1(2) * u1(sample_index - 1) + ...
            theta1(3);
    end

    fprintf( ...
        '1,%d,%.4f,%.10f,NaN,%.10f,NaN,%.10f,%.10f,NaN,%.10g,%.10g\n', ...
        decimation, ...
        decimation * base_sample_time, ...
        theta1(1), ...
        theta1(2), ...
        theta1(3), ...
        theta1(1), ...
        root_mean_square(y1 - one_step1), ...
        root_mean_square(y1 - free_run1));

    %% Second-order affine ARX model
    x2 = zeros(0, 5);
    target2 = zeros(0, 1);

    for profile_index = 1:3
        y = training{profile_index}.y;
        u = training{profile_index}.u;
        x2 = [ ...
            x2; ...
            y(2:end-1), ...
            y(1:end-2), ...
            u(2:end-1), ...
            u(1:end-2), ...
            ones(numel(y) - 2, 1)]; %#ok<AGROW>
        target2 = [target2; y(3:end)]; %#ok<AGROW>
    end

    theta2 = x2 \ target2;
    model_poles = roots([1, -theta2(1), -theta2(2)]);

    if decimation == 5
        selected_model.a1 = theta2(1);
        selected_model.a2 = theta2(2);
        selected_model.b1 = theta2(3);
        selected_model.b2 = theta2(4);
        selected_model.bias = theta2(5);
        selected_model.sample_time = decimation * base_sample_time;
        selected_model.base_sample_time = base_sample_time;
        selected_model.execution_divider = decimation;
        selected_model.poles = model_poles;
    end
    one_step2 = y1;
    one_step2(3:end) = [ ...
        y1(2:end-1), ...
        y1(1:end-2), ...
        u1(2:end-1), ...
        u1(1:end-2), ...
        ones(numel(y1) - 2, 1)] * theta2;
    free_run2 = zeros(size(y1));
    free_run2(1:2) = y1(1:2);

    for sample_index = 3:numel(y1)
        free_run2(sample_index) = ...
            theta2(1) * free_run2(sample_index - 1) + ...
            theta2(2) * free_run2(sample_index - 2) + ...
            theta2(3) * u1(sample_index - 1) + ...
            theta2(4) * u1(sample_index - 2) + ...
            theta2(5);
    end

    fprintf( ...
        '2,%d,%.4f,%.10f,%.10f,%.10f,%.10f,%.10f,%.10f,%.10f,%.10g,%.10g\n', ...
        decimation, ...
        decimation * base_sample_time, ...
        theta2(1), ...
        theta2(2), ...
        theta2(3), ...
        theta2(4), ...
        theta2(5), ...
        model_poles(1), ...
        model_poles(2), ...
        root_mean_square(y1 - one_step2), ...
        root_mean_square(y1 - free_run2));
end

save( ...
    fullfile(project_root, 'results', 'mpc_multirate_model.mat'), ...
    'selected_model');

function value = root_mean_square(error)
    value = sqrt(mean(error .^ 2));
end
