clear;
clc;

%% Project paths
% Place this script in the project's scripts folder.
script_path = mfilename('fullpath');
scripts_dir = fileparts(script_path);
project_root = fileparts(scripts_dir);

model_file = fullfile( ...
    project_root, ...
    '02_working', ...
    'HT_ctrl_MFAPC_sweep.slx');

results_dir = fullfile(project_root, 'results');

if ~exist(results_dir, 'dir')
    mkdir(results_dir);
end

%% Load model and apply the final controller parameters
load_system(model_file);
model = 'HT_ctrl_MFAPC_sweep';

set_param(model, 'FastRestart', 'off');
set_param([model '/Abs1'], 'ZeroCross', 'off');

% Parameter order:
% [lambda, rho, alpha_r, du_limit, eta, mu, alpha_d]
final_controller_params = [2.40, 0.32, 0.18, 0.030, 0.06, 0.08, 0.08];
controller_params = final_controller_params;

save( ...
    fullfile(results_dir, 'mfapc_final_parameters.mat'), ...
    'controller_params');

%% Reference-step blocks
step_0_block = [model '/wref step'];
step_20_block = [model '/wref step1'];
step_35_block = [model '/wref step2'];

required_blocks = {step_0_block, step_20_block, step_35_block};

for block_index = 1:numel(required_blocks)
    if getSimulinkBlockHandle(required_blocks{block_index}) == -1
        error('Required block was not found: %s', required_blocks{block_index});
    end
end

% Preserve the model's current step values. They are restored automatically
% when this script finishes or stops because of an error.
original_step_0 = get_param(step_0_block, 'After');
original_step_20 = get_param(step_20_block, 'After');
original_step_35 = get_param(step_35_block, 'After');

cleanup_object = onCleanup(@() restore_step_values( ...
    step_0_block, ...
    step_20_block, ...
    step_35_block, ...
    original_step_0, ...
    original_step_20, ...
    original_step_35)); %#ok<NASGU>

%% Operating-condition test matrix
% Columns are the Step-block "After" values at 0 s, 20 s, and 35 s.
% Target20 = Step0 + Step20; Target35 = Step0 + Step20 + Step35.
scenario_name = [ ...
    "nominal_up"; ...
    "small_up"; ...
    "high_output_up"; ...
    "large_middle_small_final"; ...
    "rise_then_drop"; ...
    "small_rise_then_drop"];

scenario_description = [ ...
    "Original 0.50 to 0.75 to 0.90 reference"; ...
    "Smaller increases: 0.50 to 0.65 to 0.75"; ...
    "Higher final output: 0.50 to 0.80 to 0.95"; ...
    "Large 20 s increase, then a small increase to 0.90"; ...
    "Increase to 0.75, then decrease to 0.60"; ...
    "Increase to 0.65, then decrease to 0.55"];

step_values = [ ...
     0.50, 0.25,  0.15; ...
     0.50, 0.15,  0.10; ...
     0.50, 0.30,  0.15; ...
     0.50, 0.35,  0.05; ...
     0.50, 0.25, -0.15; ...
     0.50, 0.15, -0.10];

number_of_cases = size(step_values, 1);
target_20 = step_values(:, 1) + step_values(:, 2);
target_35 = sum(step_values, 2);

%% Prepare result variables
IAE = NaN(number_of_cases, 1);
ITAE = NaN(number_of_cases, 1);
DirectionalOvershoot20 = NaN(number_of_cases, 1);
DirectionalOvershoot35 = NaN(number_of_cases, 1);
SettlingTime35 = NaN(number_of_cases, 1);
SteadyMean = NaN(number_of_cases, 1);
SteadyError = NaN(number_of_cases, 1);
SteadyFluctuation = NaN(number_of_cases, 1);
Status = strings(number_of_cases, 1);
ErrorMessage = strings(number_of_cases, 1);

%% Run all operating-condition tests
for case_number = 1:number_of_cases

    controller_params = final_controller_params;

    set_param( ...
        step_0_block, ...
        'After', ...
        num2str(step_values(case_number, 1), 17));

    set_param( ...
        step_20_block, ...
        'After', ...
        num2str(step_values(case_number, 2), 17));

    set_param( ...
        step_35_block, ...
        'After', ...
        num2str(step_values(case_number, 3), 17));

    fprintf( ...
        '\nRunning case %d of %d: %s\n', ...
        case_number, ...
        number_of_cases, ...
        scenario_name(case_number));

    try
        out = sim(model, 'ReturnWorkspaceOutputs', 'on');

        t = out.tout;
        y = squeeze(out.y_mfapc);

        iae_data = out.IAE_mfapc_20_50;
        itae_data = out.ITAE_mfapc_20_50;

        IAE(case_number) = iae_data(end);
        ITAE(case_number) = itae_data(end);

        %% Directional overshoot after the 20-second change
        index_20 = (t >= 20) & (t < 35);
        local_y_20 = y(index_20);

        DirectionalOvershoot20(case_number) = directional_overshoot( ...
            local_y_20, ...
            target_20(case_number), ...
            step_values(case_number, 2));

        %% Directional overshoot after the 35-second change
        index_35 = (t >= 35) & (t <= 50);
        local_t_35 = t(index_35);
        local_y_35 = y(index_35);

        DirectionalOvershoot35(case_number) = directional_overshoot( ...
            local_y_35, ...
            target_35(case_number), ...
            step_values(case_number, 3));

        %% Two-percent settling time after 35 seconds
        tolerance = 0.02 * max(abs(target_35(case_number)), eps);

        last_bad = find( ...
            abs(local_y_35 - target_35(case_number)) > tolerance, ...
            1, ...
            'last');

        if isempty(last_bad)
            SettlingTime35(case_number) = 0;
        elseif last_bad < length(local_t_35)
            SettlingTime35(case_number) = local_t_35(last_bad + 1) - 35;
        else
            SettlingTime35(case_number) = NaN;
        end

        %% Steady-state performance from 45 to 50 seconds
        index_steady = (t >= 45) & (t <= 50);
        steady_y = y(index_steady);

        SteadyMean(case_number) = mean(steady_y);
        SteadyError(case_number) = abs( ...
            SteadyMean(case_number) - target_35(case_number));
        SteadyFluctuation(case_number) = max(steady_y) - min(steady_y);

        Status(case_number) = "success";
        ErrorMessage(case_number) = "";

    catch simulation_error
        Status(case_number) = "failed";
        ErrorMessage(case_number) = string(simulation_error.message);

        warning( ...
            'Case %d (%s) failed: %s', ...
            case_number, ...
            scenario_name(case_number), ...
            simulation_error.message);
    end
end

%% Create and save results
results_table = table( ...
    scenario_name, ...
    scenario_description, ...
    step_values(:, 1), ...
    step_values(:, 2), ...
    step_values(:, 3), ...
    target_20, ...
    target_35, ...
    IAE, ...
    ITAE, ...
    DirectionalOvershoot20, ...
    DirectionalOvershoot35, ...
    SettlingTime35, ...
    SteadyMean, ...
    SteadyError, ...
    SteadyFluctuation, ...
    Status, ...
    ErrorMessage, ...
    'VariableNames', { ...
    'Scenario', ...
    'Description', ...
    'Step0', ...
    'Step20', ...
    'Step35', ...
    'Target20', ...
    'Target35', ...
    'IAE', ...
    'ITAE', ...
    'DirectionalOvershoot20', ...
    'DirectionalOvershoot35', ...
    'SettlingTime35', ...
    'SteadyMean', ...
    'SteadyError', ...
    'SteadyFluctuation', ...
    'Status', ...
    'ErrorMessage'});

csv_file = fullfile( ...
    results_dir, ...
    'mfapc_operating_condition_results.csv');

mat_file = fullfile( ...
    results_dir, ...
    'mfapc_operating_condition_results.mat');

writetable(results_table, csv_file);
save( ...
    mat_file, ...
    'results_table', ...
    'step_values', ...
    'final_controller_params');

% Leave the final parameter vector available in the base workspace.
controller_params = final_controller_params;

disp(results_table);

fprintf('\nFinished %d operating-condition tests.\n', number_of_cases);
fprintf('Successful cases: %d\n', sum(Status == "success"));
fprintf('CSV saved to:\n%s\n', csv_file);
fprintf('MAT file saved to:\n%s\n', mat_file);

%% Local functions
function value = directional_overshoot(y, target, step_change)
    denominator = max(abs(target), eps);

    if step_change >= 0
        value = max(0, (max(y) - target) / denominator * 100);
    else
        value = max(0, (target - min(y)) / denominator * 100);
    end
end

function restore_step_values( ...
    step_0_block, ...
    step_20_block, ...
    step_35_block, ...
    original_step_0, ...
    original_step_20, ...
    original_step_35)

    if bdIsLoaded(bdroot(step_0_block))
        set_param(step_0_block, 'After', original_step_0);
        set_param(step_20_block, 'After', original_step_20);
        set_param(step_35_block, 'After', original_step_35);
    end
end
